### ISSUE TITLE
时隔四年，对《Caffeine CacheManager 如何查看命中率、监控》提出一些新的处理方式建议

### ISSUE THREAD

**Issue by houkunlin** [AmosWang0626/notes#3]
https://github.com/AmosWang0626/notes/blob/cac7eb48cde120228a26d280c1e5c04a8002de0e/frame/sping/cache/CaffeineStat.md?plain=1#L152

新方式已核实确实有用，可对全局生效，且不用增加任何Java代码，那就是修改配置文件

```yaml
spring:
  cache:
    cache-names: default
    caffeine:
      spec: maximumSize=500,expireAfterWrite=5s,recordStats
    type: caffeine
```

周六我在开发后台管理系统的时候，想开发一个缓存清理功能，一开始写的时候没想到要加入监控数据，但是在 debug 的时候发现有个 `com.github.benmanes.caffeine.cache.Cache.stats()` 方法可以获取缓存监控信息，然后就高高兴兴的加入进去了，接口功能都写好后最后发现统计数据没生效，一顿操作猛如虎，终于给我找到了方法

https://blog.houkunlin.cn/2024/08/04/spring-caffeine-cache-manager-stats-enable/

https://github.com/houkunlin/houkunlin.github.io/blob/master/source/_posts/2024-08-04-spring-caffeine-cache-manager-stats-enable.md
